name: Deploy Databricks Bundle

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: 'deploy bundle'
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Show repository contents
        run: |
          pwd
          ls -la
          find . -maxdepth 2 -type d
          
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug repository
        run: |
          pwd
          echo "==== ls ===="
          ls -la
          echo "==== find ===="
          find .
          echo "==== git files ===="
          git ls-files

      - name: Debug GitHub context
        run: |
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Ref: $GITHUB_REF"
          echo "Workspace: $GITHUB_WORKSPACE"
          git status
          git branch
          git rev-parse HEAD

      - name: Set up Python
        uses: databricks/setup-cli@main

      - run: databricks bundle deploy -t prod
        working-directory: demo_anaytics
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          DATABRICKS_BUNDLE_ENV: prod
