name: Deploy Databricks Bundle

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: 'deploy bundle'
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: databricks/setup-cli@main

      - run: |
          databricks bundle deploy -t prod
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          DATABRICKS_BUNDLE_ENV: prod
